#!/bin/sh
# lm - CMake shortcut command (debug build)

SOURCE_DIR=$(printf "%q" "$PWD") # escapes the dir with backslashes

mkdir -p build/debug

cd build/debug

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SOURCE_DIR -G "Unix Makefiles" ../..

make

cd ../..

rm ./tem
rm ./tas
cp ./build/debug/tem ./tem
cp ./build/debug/tas ./tas
cp ./build/debug/bin2logisim ./bin2logisim
